import { z } from 'zod'
import type { Character } from '../types/schema'

export const abilityName = z.enum([
    'strength',
    'dexterity',
    'constitution',
    'intelligence',
    'wisdom',
    'charisma',
])

export const skillName = z.enum([
    'Acrobatics',
    'Animal Handling',
    'Arcana',
    'Athletics',
    'Deception',
    'History',
    'Insight',
    'Intimidation',
    'Investigation',
    'Medicine',
    'Nature',
    'Perception',
    'Performance',
    'Persuasion',
    'Religion',
    'Sleight of Hand',
    'Stealth',
    'Survival',
])

const strings = z.array(z.string())
const score = z.number().int().min(1).max(30)

export const characterSchema: z.ZodType<Character, z.ZodTypeDef, unknown> = z.object({
    schemaVersion: z.number().int(),
    id: z.string().min(1),
    role: z.enum(['Player Character', 'NPC']),
    name: z.string(),
    nation: z.enum(['Air Nomads', 'Water Tribe', 'Earth Kingdom', 'Fire Nation']),
    lineageId: z.string(),
    level: z.number().int().min(1).max(20),
    maxHpOverride: z.number().int().min(0).nullable(),
    maxHpAdjustment: z.number().int(),
    hpRolls: z.array(z.number().int().min(1).nullable()),
    hpLost: z.number().int().min(0),
    tempHp: z.number().int().min(0),
    hitDiceUsed: z.number().int().min(0),
    deathSaves: z.object({
        successes: z.number().int().min(0).max(3),
        failures: z.number().int().min(0).max(3),
    }),
    exhaustion: z.number().int().min(0).max(6),
    resourcesUsed: z.record(z.number().int().min(0)),
    backgroundId: z.string().optional(),
    backgroundNotes: z.string(),
    personality: z.string(),
    ideals: z.string(),
    bonds: z.string(),
    flaws: z.string(),
    customBackground: z
        .object({
            name: z.string(),
            description: z.string(),
            skillProficiencies: z.array(skillName).max(2),
            toolProficiencies: strings,
            featureName: z.string(),
            featureText: z.string(),
        })
        .nullable(),
    knownTechniques: z.array(
        z.object({
            techniqueId: z.string(),
            level: z.enum(['Practiced', 'Trained', 'Mastered']),
            training: z.object({
                active: z.boolean(),
                points: z.number().int().min(0).max(5),
                dc: z.number().int(),
                masteryDc: z.number().int(),
            }),
        }),
    ),
    notes: z.string(),
    species: z.enum(['none', 'human', 'variant-human']),
    abilityOption: z.boolean(),
    speciesAbilityChoices: z.array(abilityName).max(2),
    speciesSkill: skillName.nullable(),
    strength: score,
    dexterity: score,
    constitution: score,
    intelligence: score,
    wisdom: score,
    charisma: score,
    savingThrowProficiencies: z.array(abilityName),
    skillProficiencies: z.array(skillName),
    classSkillChoices: z.array(skillName),
    toolProficiencies: strings,
    languages: strings,
    selectedFeatureIds: strings,
    classId: z.string(),
    subclassId: z.string().optional(),
    lineageSkillChoices: z.array(skillName).optional(),
    lineageSavingThrowChoices: z.array(abilityName).optional(),
    lineageToolChoices: strings.optional(),
    lineageFavoredTerrains: strings.optional(),
    manualSavingThrows: z.array(abilityName).optional(),
    manualSkills: z.array(skillName).optional(),
    manualTools: strings.optional(),
    manualLanguages: strings.optional(),
    migrationNotes: strings,
    armorName: z.string(),
    armorId: z.string(),
    hasShield: z.boolean(),
    weapons: z.array(
        z.object({
            id: z.string().min(1),
            weaponId: z.string(),
            bonus: z.number().int().min(-5).max(10),
        }),
    ),
    weaponNotes: z.string(),
    inventoryItems: strings,
    currency: z.string(),
    equipmentNotes: z.string(),
})
