// GENERATED by scripts/extract-techniques.mjs from the gmbinder source. Do not edit by hand.
// Weaponsmaster Fighting Techniques (Basic = Practiced).
import type { Technique } from '../../types/schema'

export const fightingTechniques: Technique[] = [
    {
        "id": "fighting-archer",
        "name": "Archer",
        "element": "Fighting",
        "rare": false,
        "castingTime": "",
        "range": "",
        "components": "",
        "duration": "",
        "concentration": false,
        "description": "Gain a +1 on attack rolls with a ranged weapon.",
        "levelText": {
            "Practiced": "Gain a +1 on attack rolls with a ranged weapon.",
            "Trained": "Gain a bonus on your attack rolls with a ranged weapon equal to your Technique Bonus.",
            "Mastered": "Gain a bonus on your attack rolls with a ranged weapon equal to your Technique Bonus."
        }
    },
    {
        "id": "fighting-two-handed-fighting",
        "name": "Two Handed Fighting",
        "element": "Fighting",
        "rare": false,
        "castingTime": "",
        "range": "",
        "components": "",
        "duration": "",
        "concentration": false,
        "description": "When you are using both hands to use a weapon that doesn’t have the Two Hands property, add +2 to your damage rolls. Before an attack, state to the GM that you are using this Fighting Technique.",
        "levelText": {
            "Practiced": "When you are using both hands to use a weapon that doesn’t have the Two Hands property, add +2 to your damage rolls. Before an attack, state to the GM that you are using this Fighting Technique.",
            "Trained": "When you are using both hands to use a weapon that doesn’t have the Two Hands property, add your Technique Bonus to your damage rolls. Before an attack, state to the GM that you are using this Fighting Technique.",
            "Mastered": "When you are using both hands to use a weapon that doesn’t have the Two Hands property, you can add your Technique Bonus to your damage rolls. Before an attack, state to the GM that you are using this Fighting Technique."
        }
    },
    {
        "id": "fighting-thrown-weapon-fighting",
        "name": "Thrown Weapon Fighting",
        "element": "Fighting",
        "rare": false,
        "castingTime": "",
        "range": "",
        "components": "",
        "duration": "",
        "concentration": false,
        "description": "When using a thrown weapon, you can attack twice with 1 attack.",
        "levelText": {
            "Practiced": "When using a thrown weapon, you can attack twice with 1 attack.",
            "Trained": "When using a thrown weapon, you can attack two times with 1 attack. The second attack deals additional damage equal to your Technique Bonus.",
            "Mastered": "When using a thrown weapon, you can attack three times with 1 attack and gain bonus damage equal to your Technique Bonus on the second and third attack."
        }
    },
    {
        "id": "fighting-two-weapon-fighting",
        "name": "Two-Weapon Fighting",
        "element": "Fighting",
        "rare": false,
        "castingTime": "",
        "range": "",
        "components": "",
        "duration": "",
        "concentration": false,
        "description": "When you engage with two-weapons during combat, you can add your ability modifier to the damage of the second attack.",
        "levelText": {
            "Practiced": "When you engage with two-weapons during combat, you can add your ability modifier to the damage of the second attack.",
            "Trained": "When you engage with two-weapons during combat, you can add your Ability Modifier and Technique Bonus to the damage of the second attack.",
            "Mastered": "When you engage with two-weapons during combat, you can add your Ability Modifier and Technique Bonus to the damage of the second attack and you can make 1 extra attack with your second weapon."
        }
    },
    {
        "id": "fighting-protector",
        "name": "Protector",
        "element": "Fighting",
        "rare": false,
        "castingTime": "",
        "range": "",
        "components": "",
        "duration": "",
        "concentration": false,
        "description": "When a creature you see attacks a target other than you that is within 5ft of you, you can use a reaction or Combat Expertise point to leap in front of the attack and choose to block it:\n* If the attack roll is lower than your AC the attack will be blocked.\n* If the attack roll is equal to or greater than your AC, you take the damage instead.",
        "levelText": {
            "Practiced": "When a creature you see attacks a target other than you that is within 5ft of you, you can use a reaction or Combat Expertise point to leap in front of the attack and choose to block it:\n* If the attack roll is lower than your AC the attack will be blocked.\n* If the attack roll is equal to or greater than your AC, you take the damage instead.",
            "Trained": "When a creature you see attacks a target other than you that is within 5ft of you, you can use a reaction or Combat Expertise point to leap in front of the attack and choose to block it:\n* If the attack roll is lower than your AC the attack will be blocked.\n* If the attack roll is equal to or greater than your AC, the damage you take is reduced by 1d6 + your Technique Bonus.",
            "Mastered": "When a creature you see attacks a target other than you that is within 5ft of you, you can use a reaction or Combat Expertise point to leap in front of the attack and choose to block it:\n* If the attack roll is lower than your AC the attack will be blocked.\n* If the attack roll is equal to or greater than your AC, the damage you take is reduced by 1d12 + your Technique Bonus."
        }
    },
    {
        "id": "fighting-shield-attacker",
        "name": "Shield Attacker",
        "element": "Fighting",
        "rare": false,
        "castingTime": "",
        "range": "",
        "components": "",
        "duration": "",
        "concentration": false,
        "prerequisite": "Requires Shield",
        "description": "While you have a shield equipped, attacks you make with your shield deal 1d6 + your Strength Modifier damage.",
        "levelText": {
            "Practiced": "While you have a shield equipped, attacks you make with your shield deal 1d6 + your Strength Modifier damage.",
            "Trained": "While you have a shield equipped, attacks you make with your shield deal 1d6 + your Strength Modifier and Technique Bonus damage.",
            "Mastered": "While you have a shield equipped, attacks you make with your shield deal 1d10 + your Strength Modifier and Technique Bonus damage."
        }
    },
    {
        "id": "fighting-backstabber",
        "name": "Backstabber",
        "element": "Fighting",
        "rare": false,
        "castingTime": "",
        "range": "",
        "components": "",
        "duration": "",
        "concentration": false,
        "description": "While you are flanking a creature and attacking it, on hit you deal 2d6 + your weapon ability modifier extra damage.",
        "levelText": {
            "Practiced": "While you are flanking a creature and attacking it, on hit you deal 2d6 + your weapon ability modifier extra damage.",
            "Trained": "While you are flanking a creature and attacking it, on hit you deal 3d6 + your Technique Bonus extra damage.",
            "Mastered": "While you are flanking a creature and attacking it, on hit you deal 5d6 + your Technique Bonus extra damage."
        }
    },
    {
        "id": "fighting-team-player",
        "name": "Team Player",
        "element": "Fighting",
        "rare": false,
        "castingTime": "",
        "range": "",
        "components": "",
        "duration": "",
        "concentration": false,
        "description": "While a creature that you consider friendly is attacking the same creature as you, when you attack the same creature on your turn, as a reaction or by spending a Combat Expertise Point gain +1 to your attack and damage rolls.",
        "levelText": {
            "Practiced": "While a creature that you consider friendly is attacking the same creature as you, when you attack the same creature on your turn, as a reaction or by spending a Combat Expertise Point gain +1 to your attack and damage rolls.",
            "Trained": "While a creature that you consider friendly is attacking the same creature as you, when you attack the same creature on your turn, as a reaction or by spending a Combat Expertise Point gain a bonus equal to your Technique Bonus on your attack and damage rolls.",
            "Mastered": "While a creature that you consider friendly is attacking the same creature as you, when you attack the same creature on your turn, as a reaction or by spending a Combat Expertise Point gain a bonus equal to your Technique Bonus on your attack and damage rolls."
        }
    },
    {
        "id": "fighting-interruptor",
        "name": "Interruptor",
        "element": "Fighting",
        "rare": false,
        "castingTime": "",
        "range": "",
        "components": "",
        "duration": "",
        "concentration": false,
        "description": "As a reaction or by spending a Combat Expertise Point, strike at a creature and roll 1d4. The attack roll of that creature is decreased by that amount. If you attempt to interrupt a technique, then the damage is halved if the technique doesn’t require a Bending Attack Roll.",
        "levelText": {
            "Practiced": "As a reaction or by spending a Combat Expertise Point, strike at a creature and roll 1d4. The attack roll of that creature is decreased by that amount. If you attempt to interrupt a technique, then the damage is halved if the technique doesn’t require a Bending Attack Roll.",
            "Trained": "As a reaction or by spending a Combat Expertise Point, strike at a creature and roll 1d6 + your Technique Bonus. The attack roll of that creature is decreased by that amount.  If you attempt to interrupt a technique, then the damage is halved if the technique doesn’t require a Bending Attack Roll.",
            "Mastered": "As a reaction or by spending a Combat Expertise Point, strike at a creature and roll 1d10 + your Technique Bonus. The attack roll of that creature is decreased by that amount."
        }
    },
    {
        "id": "fighting-parry",
        "name": "Parry",
        "element": "Fighting",
        "rare": false,
        "castingTime": "",
        "range": "",
        "components": "",
        "duration": "",
        "concentration": false,
        "description": "When you are attacked, as a reaction or by spending a Combat Expertise Point, you can make an attack roll. If your attack roll is at least equal to the creatures attack roll, you parry that attack and take half damage.",
        "levelText": {
            "Practiced": "When you are attacked, as a reaction or by spending a Combat Expertise Point, you can make an attack roll. If your attack roll is at least equal to the creatures attack roll, you parry that attack and take half damage.",
            "Trained": "When you are attacked, as a reaction or by spending a Combat Expertise Point, you can make an attack roll. If your attack roll is greater than the creature attacking you, you parry that attack and take no damage. If it's equal to the attack roll, you parry and take half damage.",
            "Mastered": "When you are attacked, as a reaction or by spending a Combat Expertise Point, you can make an attack roll. If your attack roll is greater than the creature attacking you, you parry that attack, take no damage and deal 1d4 + your Technique Bonus damage to the creature. If it's equal, you only parry and take no damage."
        }
    },
    {
        "id": "fighting-opportunist",
        "name": "Opportunist",
        "element": "Fighting",
        "rare": false,
        "castingTime": "",
        "range": "",
        "components": "",
        "duration": "",
        "concentration": false,
        "description": "If a creature that is hostile towards you or a friendly creature, fails a Saving Throw- as a reaction or by spending a Combat Expertise point you can make an attack on the hostile creature if they are within range.",
        "levelText": {
            "Practiced": "If a creature that is hostile towards you or a friendly creature, fails a Saving Throw- as a reaction or by spending a Combat Expertise point you can make an attack on the hostile creature if they are within range.",
            "Trained": "If a creature that is hostile towards you or a friendly creature, fails a Saving Throw- as a reaction or by spending a Combat Expertise point you can make an attack by adding your Technique Bonus to the roll, on the hostile creature if they are within range.",
            "Mastered": "If a creature that is hostile towards you or a friendly creature, fails a Saving Throw- as a reaction or by spending a Combat Expertise point you can make an attack by adding your Technique Bonus to the attack and damage roll, on the hostile creature if they are within range."
        }
    },
    {
        "id": "fighting-grappler",
        "name": "Grappler",
        "element": "Fighting",
        "rare": false,
        "castingTime": "",
        "range": "",
        "components": "",
        "duration": "",
        "concentration": false,
        "description": "As a part of your action, if you have a free hand you can attempt to Grapple a creature. If you manage to grapple the creature, you grapple them with your free hand and can continue to attack with your other hand at disadvantage.",
        "levelText": {
            "Practiced": "As a part of your action, if you have a free hand you can attempt to Grapple a creature. If you manage to grapple the creature, you grapple them with your free hand and can continue to attack with your other hand at disadvantage.",
            "Trained": "As a part of your action, if you have a free hand you can attempt to Grapple a creature. If you manage to grapple the creature, you grapple them with your free hand and can continue to attack with your other hand normally.",
            "Mastered": "As a part of your action, if you have a free hand you can attempt to Grapple a creature. If you manage to grapple the creature, you grapple them with your free hand, can continue to attack with your other hand normally and the creature provides you with a half-cover bonus. If you choose to attack the grappled creature, your attacks automatically critical."
        }
    },
    {
        "id": "fighting-pummeler",
        "name": "Pummeler",
        "element": "Fighting",
        "rare": false,
        "castingTime": "",
        "range": "",
        "components": "",
        "duration": "",
        "concentration": false,
        "description": "When you take the attack action, you can expend all of your attacks within the action to attack once with an increase in damage. If your attack hits, you deal an additional damage die of that weapon.",
        "levelText": {
            "Practiced": "When you take the attack action, you can expend all of your attacks within the action to attack once with an increase in damage. If your attack hits, you deal an additional damage die of that weapon.",
            "Trained": "When you take the attack action, you can expend all of your attacks within the action to attack once with an increase in damage. If your attack hits, you deal two additional damage die of that weapon.",
            "Mastered": "When you take the attack action, you can expend all of your attacks within the action to attack once with an increase in damage. If your attack hits, you deal three additional damage die of that weapon."
        }
    },
    {
        "id": "fighting-intimidator",
        "name": "Intimidator",
        "element": "Fighting",
        "rare": false,
        "castingTime": "",
        "range": "",
        "components": "",
        "duration": "",
        "concentration": false,
        "description": "When you hit a creature, you can instill fear in them. The creature you hit must make a Wisdom Saving Throw with DC 14. On a fail, they are frightened by you. On a success, they aren't frightened. A creature that has been frightened or succeeded their save can’t be frightened by using this Fighting Technique for 24 hours. They can attempt to shrug off the fear at the start of each of their turns by repeating the Saving Throw.",
        "levelText": {
            "Practiced": "When you hit a creature, you can instill fear in them. The creature you hit must make a Wisdom Saving Throw with DC 14. On a fail, they are frightened by you. On a success, they aren't frightened. A creature that has been frightened or succeeded their save can’t be frightened by using this Fighting Technique for 24 hours. They can attempt to shrug off the fear at the start of each of their turns by repeating the Saving Throw.",
            "Trained": "When you hit a creature, you can instill fear in them. The creature you hit must make a Wisdom Saving Throw with DC 17. On a fail, they are frightened by you and you can additionally add your Technique Bonus to your attack rolls vs that creature. On a success, they aren't frightened. A creature that has been frightened or succeeded their save can’t be frightened by using this Fighting Technique for 24 hours. They can attempt to shrug off the fear at the start of each of their turns by repeating the Saving Throw.",
            "Mastered": "When you hit a creature, you can instill fear in them. The creature you hit must make a Wisdom Saving Throw with DC 20. On a fail, they are frightened by you and you can additionally add your Technique Bonus to your attack rolls vs that creature. On a success, they aren't frightened and you do not gain the bonus.. A creature that has been frightened or succeeded in their save can be frightened twice in 24 hours by using this Fighting Technique. They can attempt to shrug off the fear at the start of each of their turns by repeating the Saving Throw."
        }
    },
    {
        "id": "fighting-haphazard",
        "name": "Haphazard",
        "element": "Fighting",
        "rare": false,
        "castingTime": "",
        "range": "",
        "components": "",
        "duration": "",
        "concentration": false,
        "description": "You attack a creature without careful calculation. You can choose to make two attacks with one attack. Each attack gains a -2 to their attack roll.",
        "levelText": {
            "Practiced": "You attack a creature without careful calculation. You can choose to make two attacks with one attack. Each attack gains a -2 to their attack roll.",
            "Trained": "You attack a creature without careful calculation. You can choose to make three attacks with one attack. Each attack gains a -4 to their attack roll.",
            "Mastered": "You attack a creature without careful calculation. You can choose to make three attacks with one attack. Each attack gains a -5 to their attack roll. Each attack that hits deals additional damage equal to your Technique Bonus."
        }
    },
    {
        "id": "fighting-unarmed-fighting",
        "name": "Unarmed Fighting",
        "element": "Fighting",
        "rare": false,
        "castingTime": "",
        "range": "",
        "components": "",
        "duration": "",
        "concentration": false,
        "description": "You choose to use your own strength instead of the assist of weaponry. Your unarmed strikes deal 1d4 + your Strength Modifier bludgeoning damage.",
        "levelText": {
            "Practiced": "You choose to use your own strength instead of the assist of weaponry. Your unarmed strikes deal 1d4 + your Strength Modifier bludgeoning damage.",
            "Trained": "You choose to use your own strength instead of the assist of weaponry. Your unarmed strikes deal 1d6 + your Technique Bonus bludgeoning damage.",
            "Mastered": "You choose to use your own strength instead of the assist of weaponry. Your unarmed strikes deal 1d8 + your Technique Bonus bludgeoning damage."
        }
    },
    {
        "id": "fighting-chi-blocker",
        "name": "Chi Blocker",
        "element": "Fighting",
        "rare": false,
        "castingTime": "",
        "range": "",
        "components": "",
        "duration": "",
        "concentration": false,
        "description": "With precise strikes you aim to subdue hostiles. When you attack with an unarmed strike, you can choose to block the chi paths of a creature. Each strike you make counts as an Unarmed Strike and you have to roll separately for each strike. Each limb has 3 chi points:\nFor Arms:\n* If you block 1 chi point, the target isn’t affected.\n* If you block 2 chi points, the target has disadvantage on attack rolls\n* If you block 3 chi points, the target can only attempt to Unarmed Strike using that arm and can not bend using that arm.\n* If you block both arms, the target can only attempt to Unarmed Strike at disadvantage.\nFor Legs:\n* If you block 1 chi point, the target isn’t affected.\n* If you block 2 chi points, the target has disadvantage on Saving Throws\n* If you block 3 chi points, the target uses twice their movement per 5ft and can not bend using that arm.\n* If you block both legs, the target falls prone and remains prone until the Chi Clotting effect ends.",
        "levelText": {
            "Practiced": "With precise strikes you aim to subdue hostiles. When you attack with an unarmed strike, you can choose to block the chi paths of a creature. Each strike you make counts as an Unarmed Strike and you have to roll separately for each strike. Each limb has 3 chi points:\nFor Arms:\n* If you block 1 chi point, the target isn’t affected.\n* If you block 2 chi points, the target has disadvantage on attack rolls\n* If you block 3 chi points, the target can only attempt to Unarmed Strike using that arm and can not bend using that arm.\n* If you block both arms, the target can only attempt to Unarmed Strike at disadvantage.\nFor Legs:\n* If you block 1 chi point, the target isn’t affected.\n* If you block 2 chi points, the target has disadvantage on Saving Throws\n* If you block 3 chi points, the target uses twice their movement per 5ft and can not bend using that arm.\n* If you block both legs, the target falls prone and remains prone until the Chi Clotting effect ends.",
            "Trained": "With precise strikes you aim to subdue hostiles. When you attack with an unarmed strike, you can choose to block the chi paths of a creature. Each strike you make counts as an Unarmed Strike and you have to roll separately for each strike. You can reroll the lowest attack roll but you must use that roll. Each limb has 3 chi points:\nFor Arms:\n* If you block 1 chi point, the target isn’t affected.\n* If you block 2 chi points, the target has disadvantage on attack rolls\n* If you block 3 chi points, the target can only attempt to Unarmed Strike using that arm and can not bend using that arm.\n* If you block both arms, the target can only attempt to Unarmed Strike at disadvantage.\nFor Legs:\n* If you block 1 chi point, the target isn’t affected.\n* If you block 2 chi points, the target has disadvantage on Saving Throws\n* If you block 3 chi points, the target uses twice their movement per 5ft and can not bend using that arm.\n* If you block both legs, the target falls prone and remains prone until the Chi Clotting effect ends.",
            "Mastered": "With precise strikes you aim to subdue hostiles. When you attack with an unarmed strike, you can choose to block the chi paths of a creature. Each strike you make counts as an Unarmed Strike and you have to roll separately for each strike. Attack rolls that are lower than 10 are considered as 10. Each limb has 3 chi points:\nFor Arms:\n* If you block 1 chi point, the target isn’t affected.\n* If you block 2 chi points, the target has disadvantage on attack rolls\n* If you block 3 chi points, the target can only attempt to Unarmed Strike using that arm and can not bend using that arm.\n* If you block both arms, the target can only attempt to Unarmed Strike at disadvantage.\nFor Legs:\n* If you block 1 chi point, the target isn’t affected.\n* If you block 2 chi points, the target has disadvantage on Saving Throws\n* If you block 3 chi points, the target uses twice their movement per 5ft and can not bend using that arm.\n* If you block both legs, the target falls prone and remains prone until the Chi Clotting effect ends."
        }
    },
    {
        "id": "fighting-fortifier",
        "name": "Fortifier",
        "element": "Fighting",
        "rare": false,
        "castingTime": "",
        "range": "",
        "components": "",
        "duration": "",
        "concentration": false,
        "prerequisite": "Requires Shield",
        "description": "You can place your shield on the ground and hide behind  it to create half-cover for a creature. Creatures can remove the shield from the ground as a bonus action.If the shield is placed, the shield has 14 AC and 30 HP. When the HP of the shield reaches 0, it is knocked over and no longer provides cover bonus.",
        "levelText": {
            "Practiced": "You can place your shield on the ground and hide behind  it to create half-cover for a creature. Creatures can remove the shield from the ground as a bonus action.If the shield is placed, the shield has 14 AC and 30 HP. When the HP of the shield reaches 0, it is knocked over and no longer provides cover bonus.",
            "Trained": "You can place your shield on the ground and hide behind  it to create ¾ cover for a creature. Creatures can remove the shield from the ground as a bonus action. If the shield is placed, the shield has 17 AC and 30 HP. When the HP of the shield reaches 0, it is knocked over and no longer provides cover bonus.",
            "Mastered": "You can place your shield on the ground and hide behind it to create ¾ cover for a creature. Only you can remove the shield. You can remove the shield as a bonus action."
        }
    },
    {
        "id": "fighting-ricochet",
        "name": "Ricochet",
        "element": "Fighting",
        "rare": false,
        "castingTime": "",
        "range": "",
        "components": "",
        "duration": "",
        "concentration": false,
        "prerequisite": "Thrown Weapons Only",
        "description": "You throw your weapon in such a way that not only do you hit a creature, you also make it ricochet back to your hand. You must be within the maximum range of the weapon to use this.",
        "levelText": {
            "Practiced": "You throw your weapon in such a way that not only do you hit a creature, you also make it ricochet back to your hand. You must be within the maximum range of the weapon to use this.",
            "Trained": "You throw your weapon in such a way that you can hit two different creatures that are at most 10 ft apart before the weapon returns back to you. You only roll 1 attack and damage roll for the attack, the attack and damage roll apply to both creatures. You must be within the maximum range of the weapon to use this.",
            "Mastered": "You throw your weapon in such a way that you can hit three different creatures that are each within 10 ft of each other before the weapon returns back to you. You only roll 1 attack and damage roll for the attack, the attack and damage roll apply to both creatures. If you think the attack won’t hit, you can reroll the attack roll but you must use the new roll. You must be within the maximum range of the weapon to use this."
        }
    }
]
