// GENERATED by scripts/extract-techniques.mjs from the gmbinder source. Do not edit by hand.
// Universal techniques (any class).
import type { Technique } from '../../types/schema'

export const universalTechniques: Technique[] = [
    {
        "id": "universal-cutting-words",
        "name": "Cutting Words",
        "element": "Universal",
        "rare": false,
        "castingTime": "1 Reaction",
        "range": "60ft",
        "components": "V",
        "duration": "Instantaneous",
        "concentration": false,
        "description": "Use your wit to distract, confuse, and otherwise sap the confidence and competence of others. When a creature that you can see within 60 feet of you makes an attack roll, an ability check, or technique damage, you can use your reaction to subtract 1d10 from the number rolled from the creature's roll. You can choose to use this feature after the creature makes its roll, but before the DM determines whether the attack roll or ability check succeeds or fails, or before the creature deals its damage. The creature is immune if it can't hear you."
    },
    {
        "id": "universal-do-the-thing",
        "name": "Do the Thing",
        "element": "Universal",
        "rare": false,
        "castingTime": "1 Turn",
        "range": "60ft",
        "components": "V, S",
        "duration": "Instantaneous",
        "concentration": false,
        "description": "You scream out at a friendly creature that can hear you to do the thing. Until the start of your next turn, that friendly creature can use their reaction to use any technique that has a casting time of less than 1 turn."
    },
    {
        "id": "universal-fear",
        "name": "Fear",
        "element": "Universal",
        "rare": false,
        "castingTime": "1 Action",
        "range": "60ft",
        "components": "V, S",
        "duration": "Instantaneous",
        "concentration": false,
        "description": "Embed fear into every creature that can see you in a display of power. You show off  your ruthlessness upon a creature that can see or hear you. The creature must make a Wisdom Saving Throw. On a fail, the creature is Frightened and has disadvantage on attacks and ability checks as long as you remain in their line of sight. At the end of their turn, the creature can make another Wisdom Saving Throw to shrug off the effect. If the creature succeeds on its saving throw, you can't use this feature on that creature again for 24 hours."
    },
    {
        "id": "universal-mending",
        "name": "Mending",
        "element": "Universal",
        "rare": false,
        "castingTime": "1 Action",
        "range": "Touch",
        "components": "S, M",
        "duration": "Instantaneous",
        "concentration": false,
        "description": "You repair a single break or tear in an object you touch, such as a broken chain link, two halves of a broken key, a torn cloak, or a leaking wineskin. As long as the break or tear is no larger than 4 feet in any dimension, you mend it by bending your respective element or by using components, leaving no trace of the former damage."
    },
    {
        "id": "universal-monologue",
        "name": "Monologue",
        "element": "Universal",
        "rare": false,
        "castingTime": "1 Action",
        "range": "60ft",
        "components": "V",
        "duration": "Instantaneous",
        "concentration": false,
        "description": "Rant a bit about yourself to discourage your foes in the middle of combat. When you use this technique, until the start of your next turn you gain a 1d10 die. Until the start of your next turn you can choose to roll this die and add it to an attack roll, saving throw, skill check or technique damage. Once your next turn starts, you can no longer use this die."
    },
    {
        "id": "universal-motivational-speech",
        "name": "Motivational Speech",
        "element": "Universal",
        "rare": false,
        "castingTime": "1 Action",
        "range": "60ft",
        "components": "V",
        "duration": "3 hours",
        "concentration": false,
        "description": "Make an inspiring speech to friendly creatures that can hear you. Every friendly creature that can hear and understand you gains 1d12 + your Charisma Modifier (minimum of 5) temporary HP and has advantage on Wisdom Saving Throws for the duration."
    },
    {
        "id": "universal-taunt",
        "name": "Taunt",
        "element": "Universal",
        "rare": false,
        "castingTime": "1 Bonus Action",
        "range": "30ft",
        "components": "V",
        "duration": "3 hours",
        "concentration": false,
        "description": "You attempt to compel a creature into attacking you. One creature that can see or hear you within range must make a Wisdom Saving Throw. On a failed save, the creature succumbs to your taunting and starts to attack you. On a success, the creature has -1 to all attacks, techniques and damages it deals. If one creature uses this technique more than once on  the same creature, the effect doubles and stacks (i.e if you use it on your next turn, you apply -2 for a total of -3). The effect ends if you attack any other creature."
    },
    {
        "id": "universal-vicious-mockery",
        "name": "Vicious Mockery",
        "element": "Universal",
        "rare": false,
        "castingTime": "1 Action",
        "range": "60ft",
        "components": "V",
        "duration": "Instantaneous",
        "concentration": false,
        "description": "You unleash a string of insults at a creature you can see within range. If the target can hear you, it must succeed on a Wisdom saving throw or take 1d4 psychic damage and have disadvantage on the next attack roll or technique saving throw, whichever comes first, it makes before the end of its next turn. At Trained level, the creature has disadvantage on 2 attacks or saving throws until the end of its next turn. At Mastered level, the creature has disadvantage on 3 attacks or saving throws until the end of its next turn."
    }
]
